#!/usr/bin/env node
import { input } from '@inquirer/prompts';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

// ANSI Color Codes
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  bold: '\x1b[1m',
};

const MIGRATION_DESTINATION_FILENAME = '0000_initial_schema.sql';

const getPackageJsonTemplate = (projectName: string) => `
{
  "name": "${projectName}",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    "deploy": "wrangler deploy",
    "db:create": "wrangler d1 create",
    "db:migrate": "wrangler d1 migrations apply",
    "dev": "wrangler dev",
    "logs": "wrangler tail"
  },
  "dependencies": {
    "workflow-cloudflare-world": "4.0.1-beta.12"
  },
  "devDependencies": {
    "wrangler": "latest"
  }
}
`;

const getWranglerTomlTemplate = (config: {
  workerName: string;
  d1Binding: string;
  d1DatabaseName: string;
  workflowQueue: string;
  stepQueue: string;
  r2Bucket: string;
  serviceBinding: string;
}) => `
# This wrangler.toml file is generated by the workflow-cloudflare-world CLI.
# It configures a standalone Cloudflare runtime for executing workflows.

name = "${config.workerName}"
main = "./node_modules/workflow-cloudflare-world/dist/src/worker.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

# Bindings for the workflow system's state and orchestration
# -----------------------------------------------------------

[[d1_databases]]
binding = "${config.d1Binding}"
database_name = "${config.d1DatabaseName}"
migrations_dir = "migrations"

[[queues.producers]]
binding = "WORKFLOW_QUEUE"
queue = "${config.workflowQueue}"

[[queues.producers]]
binding = "STEP_QUEUE"
queue = "${config.stepQueue}"

[[queues.consumers]]
queue = "${config.workflowQueue}"

[[queues.consumers]]
queue = "${config.stepQueue}"

[[r2_buckets]]
binding = "STREAM_BUCKET"
bucket_name = "${config.r2Bucket}"

# Bindings for Durable Objects and Containers
# -------------------------------------------
# These are required for stream coordination and deterministic workflow execution.

[durable_objects]
bindings = [
  { name = "STREAM_COORDINATOR", class_name = "StreamCoordinator" },
  { name = "WORKFLOW_EXECUTOR", class_name = "WorkflowExecutorContainer" }
]

# Migration for the new Durable Object classes is required by Wrangler.
[[migrations]]
tag = "v1"
new_classes = ["StreamCoordinator", "WorkflowExecutorContainer"]

[[containers]]
class_name = "WorkflowExecutorContainer"
image = "./Dockerfile"

# Service binding for inter-worker communication
# ----------------------------------------------
# Your separate application workers will use this binding to securely
# communicate with this deployed workflow runtime.

[[services]]
binding = "${config.serviceBinding}"
service = "${config.workerName}"
`;

const DOCKERFILE_TEMPLATE = `# This Dockerfile is generated by the workflow-cloudflare-world CLI.
# It creates a container image for the standalone workflow runtime.

FROM node:20-alpine

WORKDIR /app

# Copy dependency manifest
COPY package.json ./

# Install production dependencies from npm
RUN npm install --omit=dev --legacy-peer-deps

# Create and switch to a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs
USER nodejs

# Cloudflare Containers will map the port automatically.
# EXPOSE 8080 is not strictly necessary but is good practice.
EXPOSE 8080

# The command to run the workflow executor.
CMD ["node", "./node_modules/workflow-cloudflare-world/dist/src/container-executor.js"]
`;

const DOCKERIGNORE_TEMPLATE = `
# Ignore all files by default
**/*

# But whitelist files needed for the build
!/package.json
`;

const GITIGNORE_TEMPLATE = `
# Dependencies
node_modules

# Wrangler
.wrangler/
.mf/

# Logs
*.log
`;

const getReadmeTemplate = (projectName: string) => `
# ${projectName}

This project contains a standalone Cloudflare Workflow Runtime, scaffolded by the \`workflow-cloudflare-world\` CLI.

## 🚀 Deployment

1.  **Install Dependencies**
    \`\`\`bash
    npm install
    \`\`\`

2.  **Create Cloudflare Resources**
    Follow the prompts from the CLI wizard. You will need to create the D1 database and other resources for the first time.

    \`\`\`bash
    # Example:
    wrangler d1 create <your-db-name>
    \`\`\`

3.  **Apply Database Migrations**
    \`\`\`bash
    wrangler d1 migrations apply <your-db-name>
    \`\`\`

4.  **Deploy**
    \`\`\`bash
    wrangler deploy
    \`\`\`

Once deployed, this service will listen for jobs on its configured Cloudflare Queues. Your separate application workers can connect to this runtime using the service binding you configured.
`;

const banner = `
${colors.bold}╭────────────────────────────────────────────────╮
│  Workflow Cloudflare World - Setup Wizard  │
╰────────────────────────────────────────────────╯${colors.reset}
`;

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args[0] !== 'init' || !args[1]) {
    console.error(
      'Usage: npx workflow-cloudflare-world@latest init <project-name>'
    );
    process.exit(1);
  }
  const projectName = args[1];
  const destPath = resolve(process.cwd(), projectName);

  try {
    await mkdir(destPath);
  } catch (e: unknown) {
    if (e && typeof e === 'object' && 'code' in e && e.code === 'EEXIST') {
      console.error(
        `\n❌ Directory "${projectName}" already exists. Please choose a different name.`
      );
      process.exit(1);
    }
    throw e;
  }

  console.log(banner);
  console.log(
    `Scaffolding a new Cloudflare Workflow Runtime in "${projectName}"...`
  );

  const workerName = await input({
    message: 'Enter a name for your worker service:',
    default: projectName,
  });
  const d1DatabaseName = await input({
    message: 'Enter a name for your D1 database:',
    default: `${projectName}-db`,
  });
  const workflowQueue = await input({
    message: 'Enter a name for the workflow queue:',
    default: `${projectName}-workflows`,
  });
  const stepQueue = await input({
    message: 'Enter a name for the step queue:',
    default: `${projectName}-steps`,
  });
  const r2Bucket = await input({
    message: 'Enter a name for the R2 bucket (for streams):',
    default: `${projectName}-streams`,
  });
  const serviceBinding = await input({
    message: 'Enter a binding name for other services to use:',
    default: 'WORKFLOW_RUNTIME',
  });

  const wranglerTomlContent = getWranglerTomlTemplate({
    workerName,
    d1Binding: 'DB',
    d1DatabaseName,
    workflowQueue,
    stepQueue,
    r2Bucket,
    serviceBinding,
  });
  const packageJsonContent = getPackageJsonTemplate(projectName);
  const readmeContent = getReadmeTemplate(projectName);

  const migrationsPath = join(destPath, 'migrations');
  await mkdir(migrationsPath);

  try {
    const __dirname = dirname(fileURLToPath(import.meta.url));
    const migrationSourcePath = resolve(
      __dirname,
      'drizzle/migrations/0000_workflow_cloudflare.sql'
    );
    const migrationContent = await readFile(migrationSourcePath, 'utf-8');
    await writeFile(
      join(migrationsPath, MIGRATION_DESTINATION_FILENAME),
      migrationContent,
      'utf-8'
    );
  } catch (error) {
    console.error('\n❌ Failed to copy database migration schema.');
    console.error(
      'Please ensure the `workflow-cloudflare-world` package was built correctly.'
    );
    console.error(error);
    process.exit(1);
  }

  const filesToWrite = [
    { path: join(destPath, 'wrangler.toml'), content: wranglerTomlContent },
    { path: join(destPath, 'package.json'), content: packageJsonContent },
    { path: join(destPath, 'Dockerfile'), content: DOCKERFILE_TEMPLATE },
    { path: join(destPath, '.dockerignore'), content: DOCKERIGNORE_TEMPLATE },
    { path: join(destPath, '.gitignore'), content: GITIGNORE_TEMPLATE },
    { path: join(destPath, 'README.md'), content: readmeContent },
  ];

  for (const file of filesToWrite) {
    await writeFile(file.path, file.content.trim(), 'utf-8');
  }

  console.log(
    `\n${colors.green}✅ Project scaffolding complete!${colors.reset}`
  );
  console.log(`\n${colors.bold}Next steps:${colors.reset}`);
  const bullet = (msg: string) => console.log(`  • ${msg}`);
  bullet(`${colors.cyan}cd ${projectName}${colors.reset}`);
  bullet(
    `Run ${colors.yellow}\`npm install\`${colors.reset} to install dependencies.`
  );
  bullet(`Run the following commands to create your Cloudflare resources:`);
  console.log(
    `    ${colors.yellow}\`wrangler d1 create ${d1DatabaseName}\`${colors.reset}`
  );
  console.log(
    `    ${colors.yellow}\`wrangler r2 bucket create ${r2Bucket}\`${colors.reset}`
  );
  console.log(
    `    ${colors.yellow}\`wrangler queues create ${workflowQueue}\`${colors.reset}`
  );
  console.log(
    `    ${colors.yellow}\`wrangler queues create ${stepQueue}\`${colors.reset}`
  );
  bullet(
    `Run ${colors.yellow}\`wrangler d1 migrations apply ${d1DatabaseName}\`${colors.reset} to set up the database schema.`
  );
  bullet(
    `Run ${colors.yellow}\`wrangler deploy\`${colors.reset} to deploy your workflow runtime.`
  );

  console.log(
    `\nAfter deploying, connect your application worker to this runtime by adding the following service binding to its ${colors.cyan}\`wrangler.toml\`${colors.reset}:`
  );
  console.log(`
${colors.yellow}[[services]]
binding = "${serviceBinding}"
service = "${workerName}"${colors.reset}
`);
}

main().catch((err) => {
  console.error('\nAn unexpected error occurred:', err);
  process.exit(1);
});
