#!/usr/bin/env node
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { input } from '@inquirer/prompts';

// --- Template for the initial database migration ---
const MIGRATION_DESTINATION_FILENAME = '0000_initial_schema.sql';

// --- Template for the generated package.json ---
const getPackageJsonTemplate = (projectName: string) => `
{
  "name": "${projectName}",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    "deploy": "wrangler deploy",
    "db:create": "wrangler d1 create",
    "db:migrate": "wrangler d1 migrations apply",
    "dev": "wrangler dev",
    "logs": "wrangler tail"
  },
  "dependencies": {
    "workflow-cloudflare-world": "latest"
  },
  "devDependencies": {
    "wrangler": "latest"
  }
}
`;

// --- Template for the generated wrangler.toml ---
const getWranglerTomlTemplate = (config: {
  workerName: string;
  d1Binding: string;
  d1DatabaseName: string;
  workflowQueue: string;
  stepQueue: string;
  r2Bucket: string;
  serviceBinding: string;
}) => `
# This wrangler.toml file is generated by the workflow-cloudflare-world CLI.
# It configures a standalone Cloudflare runtime for executing workflows.

name = "${config.workerName}"
main = "./node_modules/workflow-cloudflare-world/dist/src/worker.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

# Bindings for the workflow system's state and orchestration
# -----------------------------------------------------------

[[d1_databases]]
binding = "${config.d1Binding}"
database_name = "${config.d1DatabaseName}"
database_id = "" # wrangler will fill this in on first deploy
migrations_dir = "migrations"

[[queues.producers]]
binding = "WORKFLOW_QUEUE"
queue = "${config.workflowQueue}"

[[queues.producers]]
binding = "STEP_QUEUE"
queue = "${config.stepQueue}"

[[queues.consumers]]
queue = "${config.workflowQueue}"

[[queues.consumers]]
queue = "${config.stepQueue}"

[[r2_buckets]]
binding = "STREAM_BUCKET"
bucket_name = "${config.r2Bucket}"

# Bindings for Durable Objects and Containers
# -------------------------------------------
# These are required for stream coordination and deterministic workflow execution.

[durable_objects]
bindings = [
  { name = "STREAM_COORDINATOR", class_name = "StreamCoordinator" },
  { name = "WORKFLOW_EXECUTOR", class_name = "WorkflowExecutorContainer" }
]

[[containers]]
binding = "WORKFLOW_EXECUTOR"
image = "." # Build from the local Dockerfile

# Service binding for inter-worker communication
# ----------------------------------------------
# Your separate application workers will use this binding to securely
# communicate with this deployed workflow runtime.

[[services]]
binding = "${config.serviceBinding}"
service = "${config.workerName}"
`;

// --- Template for a generic Dockerfile for the runtime ---
const DOCKERFILE_TEMPLATE = `# This Dockerfile is generated by the workflow-cloudflare-world CLI.
# It creates a container image for the standalone workflow runtime.

FROM node:20-alpine AS base

# Install pnpm for dependency management
RUN npm install -g pnpm

WORKDIR /app

# Copy dependency manifests
COPY package.json pnpm-lock.yaml ./

# Install only production dependencies to keep the image small
RUN pnpm install --prod

# The entrypoint is the pre-built worker.js from the workflow-cloudflare-world package.
# No source code from this project needs to be copied into the image.

# Create and switch to a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs
USER nodejs

# Cloudflare Containers will map the port automatically.
# EXPOSE 8080 is not strictly necessary but is good practice.
EXPOSE 8080

# The command to run the worker.
CMD ["node", "./node_modules/workflow-cloudflare-world/dist/src/worker.js"]
`;

// --- Template for .dockerignore ---
const DOCKERIGNORE_TEMPLATE = `
# Ignore all files by default
**/*

# But whitelist files needed for the build
!/package.json
!/pnpm-lock.yaml
`;

// --- Template for .gitignore ---
const GITIGNORE_TEMPLATE = `
# Dependencies
node_modules

# Wrangler
.wrangler/
.mf/

# Logs
*.log
`;

// --- Template for the project's README ---
const getReadmeTemplate = (projectName: string) => `
# ${projectName}

This project contains a standalone Cloudflare Workflow Runtime, scaffolded by the \`workflow-cloudflare-world\` CLI.

## 🚀 Deployment

1.  **Install Dependencies**
    \`\`\`bash
    pnpm install
    \`\`\`

2.  **Create Cloudflare Resources**
    Follow the prompts from the CLI wizard. You will need to create the D1 database and other resources for the first time.

    \`\`\`bash
    # Example:
    wrangler d1 create <your-db-name>
    \`\`\`

3.  **Apply Database Migrations**
    \`\`\`bash
    wrangler d1 migrations apply <your-db-name>
    \`\`\`

4.  **Deploy**
    \`\`\`bash
    wrangler deploy
    \`\`\`

Once deployed, this service will listen for jobs on its configured Cloudflare Queues. Your separate application workers can connect to this runtime using the service binding you configured.
`;

const banner = `
╭────────────────────────────────────────────────╮
│  Workflow Cloudflare World - Setup Wizard  │
╰────────────────────────────────────────────────╯
`;

async function main(): Promise<void> {
  // Check for 'init' command and project name
  const args = process.argv.slice(2);
  if (args[0] !== 'init' || !args[1]) {
    console.error(
      'Usage: npx workflow-cloudflare-world@latest init <project-name>'
    );
    process.exit(1);
  }
  const projectName = args[1];
  const destPath = resolve(process.cwd(), projectName);

  try {
    await mkdir(destPath);
  } catch (e: unknown) {
    if (e && typeof e === 'object' && 'code' in e && e.code === 'EEXIST') {
      console.error(
        `\n❌ Directory "${projectName}" already exists. Please choose a different name.`
      );
      process.exit(1);
    }
    throw e;
  }

  console.log(banner);
  console.log(
    `Scaffolding a new Cloudflare Workflow Runtime in "${projectName}"...`
  );

  // --- Gather user configuration ---
  const workerName = await input({
    message: 'Enter a name for your worker service:',
    default: projectName,
  });
  const d1DatabaseName = await input({
    message: 'Enter a name for your D1 database:',
    default: `${projectName}-db`,
  });
  const workflowQueue = await input({
    message: 'Enter a name for the workflow queue:',
    default: `${projectName}-workflows`,
  });
  const stepQueue = await input({
    message: 'Enter a name for the step queue:',
    default: `${projectName}-steps`,
  });
  const r2Bucket = await input({
    message: 'Enter a name for the R2 bucket (for streams):',
    default: `${projectName}-streams`,
  });
  const serviceBinding = await input({
    message: 'Enter a binding name for other services to use:',
    default: 'WORKFLOW_RUNTIME',
  });

  // --- Generate file content ---
  const wranglerTomlContent = getWranglerTomlTemplate({
    workerName,
    d1Binding: 'DB', // Keep this binding name static for simplicity
    d1DatabaseName,
    workflowQueue,
    stepQueue,
    r2Bucket,
    serviceBinding,
  });
  const packageJsonContent = getPackageJsonTemplate(projectName);
  const readmeContent = getReadmeTemplate(projectName);

  // --- Write files to the new project directory ---
  const migrationsPath = join(destPath, 'migrations');
  await mkdir(migrationsPath);

  // ** FIX: Find and copy the canonical migration SQL file **
  try {
    const __dirname = dirname(fileURLToPath(import.meta.url));
    // This relative path works because the built cli.js is at `dist/src/cli.js`
    // and the migration file is copied to `dist/src/drizzle/migrations/`
    const migrationSourcePath = resolve(
      __dirname,
      '../drizzle/migrations/0000_workflow_cloudflare.sql'
    );
    const migrationContent = await readFile(migrationSourcePath, 'utf-8');
    await writeFile(
      join(migrationsPath, MIGRATION_DESTINATION_FILENAME),
      migrationContent,
      'utf-8'
    );
  } catch (error) {
    console.error('\n❌ Failed to copy database migration schema.');
    console.error(
      'Please ensure the `workflow-cloudflare-world` package was built correctly.'
    );
    console.error(error);
    process.exit(1);
  }

  const filesToWrite = [
    { path: join(destPath, 'wrangler.toml'), content: wranglerTomlContent },
    { path: join(destPath, 'package.json'), content: packageJsonContent },
    { path: join(destPath, 'Dockerfile'), content: DOCKERFILE_TEMPLATE },
    { path: join(destPath, '.dockerignore'), content: DOCKERIGNORE_TEMPLATE },
    { path: join(destPath, '.gitignore'), content: GITIGNORE_TEMPLATE },
    { path: join(destPath, 'README.md'), content: readmeContent },
  ];

  for (const file of filesToWrite) {
    await writeFile(file.path, file.content.trim(), 'utf-8');
  }

  // --- Print next steps ---
  console.log('\n✅ Project scaffolding complete!');
  console.log('\nNext steps:');
  const bullet = (msg: string) => console.log(`  • ${msg}`);
  bullet(`cd ${projectName}`);
  bullet('Run `pnpm install` to install dependencies.');
  bullet(
    `Run \`wrangler d1 create ${d1DatabaseName}\` to create your database.`
  );
  bullet(
    `Run \`wrangler d1 migrations apply ${d1DatabaseName}\` to set up the schema.`
  );
  bullet('Run `wrangler deploy` to deploy your workflow runtime.');
  console.log(
    '\nAfter deploying, connect your application worker to this runtime by adding the following service binding to its `wrangler.toml`:'
  );
  console.log(`
[[services]]
binding = "${serviceBinding}"
service = "${workerName}"
`);
}

main().catch((err) => {
  console.error('\nAn unexpected error occurred:', err);
  process.exit(1);
});
