import { join } from 'node:path';
import { readFile } from 'node:fs/promises';

// Import pre-built workflow handlers
// These files are generated by `workflow build` in ESM format
let flowHandler: any = null;
let stepHandler: any = null;
let webhookHandlers: any = null;

/**
 * Validates that a generated file is pure ESM format
 */
async function validateEsmFormat(filePath: string): Promise<void> {
  try {
    const content = await readFile(filePath, 'utf8');

    // Check for CommonJS patterns that would cause ESM errors
    if (content.includes('module.exports') || content.includes('require(')) {
      throw new Error(
        `Generated file ${filePath} contains CommonJS syntax but project uses ESM.\n` +
          `The workflow build process may have generated CommonJS files instead of ESM files.\n` +
          `Try running 'workflow build' again to generate pure ESM files.`
      );
    }
  } catch (error) {
    throw new Error(`Failed to validate file ${filePath}: ${error}`);
  }
}

/**
 * Loads flow handler from pre-built ESM file
 */
async function getFlowHandler() {
  if (!flowHandler) {
    const filePath = join(process.cwd(), '.well-known/workflow/v1/flow.js');
    await validateEsmFormat(filePath);
    const module = await import(filePath);
    flowHandler = module.POST;
  }
  return flowHandler;
}

/**
 * Loads step handler from pre-built ESM file
 */
async function getStepHandler() {
  if (!stepHandler) {
    const filePath = join(process.cwd(), '.well-known/workflow/v1/step.js');
    await validateEsmFormat(filePath);
    const module = await import(filePath);
    stepHandler = module.POST;
  }
  return stepHandler;
}

/**
 * Loads webhook handlers from pre-built ESM file
 */
async function getWebhookHandlers() {
  if (!webhookHandlers) {
    const filePath = join(process.cwd(), '.well-known/workflow/v1/webhook.js');
    await validateEsmFormat(filePath);
    const module = await import(filePath);
    webhookHandlers = module;
  }
  return webhookHandlers;
}

/**
 * Express-compatible handler for flow requests
 */
export async function handleFlow(req: any, res: any): Promise<void> {
  try {
    const handler = await getFlowHandler();
    const request = createWebRequest(req);
    const response = await handler(request);
    await sendWebResponse(res, response);
  } catch (error) {
    console.error('[workflow-express] Flow handler error:', error);
    res.status(500).send('Internal Server Error');
  }
}

/**
 * Express-compatible handler for step requests
 */
export async function handleStep(req: any, res: any): Promise<void> {
  try {
    const handler = await getStepHandler();
    const request = createWebRequest(req);
    const response = await handler(request);
    await sendWebResponse(res, response);
  } catch (error) {
    console.error('[workflow-express] Step handler error:', error);
    res.status(500).send('Internal Server Error');
  }
}

/**
 * Express-compatible handler for webhook requests
 */
export async function handleWebhook(req: any, res: any): Promise<void> {
  try {
    const handlers = await getWebhookHandlers();
    const method = req.method?.toUpperCase();
    const handler = handlers[method];

    if (!handler || typeof handler !== 'function') {
      res.status(405).send('Method Not Allowed');
      return;
    }

    const request = createWebRequest(req);
    const response = await handler(request);
    await sendWebResponse(res, response);
  } catch (error) {
    console.error('[workflow-express] Webhook handler error:', error);
    res.status(500).send('Internal Server Error');
  }
}

/**
 * Creates a Web API Request from Express request
 */
function createWebRequest(req: any): Request {
  const protocol = req.protocol || (req.secure ? 'https' : 'http');
  const host = req.get('host') ?? 'localhost';
  const url = `${protocol}://${host}${req.originalUrl ?? req.url ?? ''}`;
  const method = req.method?.toUpperCase() ?? 'GET';
  const headers = new Headers();

  // Copy headers from Express to Web API
  for (const [key, value] of Object.entries(req.headers)) {
    if (typeof value === 'undefined') continue;
    if (Array.isArray(value)) {
      for (const entry of value) {
        headers.append(key, entry);
      }
    } else {
      headers.append(key, value as string);
    }
  }

  const init: RequestInit = {
    method,
    headers,
  };

  // Add body for methods that support it
  if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(method) && req.readable) {
    init.body = req as any;
    (init as any).duplex = 'half';
  }

  return new Request(url, init);
}

/**
 * Sends a Web API Response through Express
 */
async function sendWebResponse(res: any, response: Response): Promise<void> {
  res.status(response.status);

  // Copy headers from Web API to Express
  response.headers.forEach((value: string, key: string) => {
    if (key.toLowerCase() === 'set-cookie') {
      // Handle cookies separately
      return;
    }
    res.setHeader(key, value);
  });

  // Handle cookies specially
  const headersWithCookies = response.headers as any;
  const cookies = headersWithCookies.getSetCookie?.();
  if (cookies && cookies.length > 0) {
    res.setHeader('set-cookie', cookies);
  }

  // Send body
  if (!response.body) {
    res.end();
    return;
  }

  // Convert Web API stream to Node.js stream
  const buffer = Buffer.from(await response.arrayBuffer());
  res.end(buffer);
}
