import type { CodemodDefinition } from './types.js';

const nitroWorkflowContent = `import { FatalError, sleep } from 'workflow';

export async function handleUserSignup(email: string) {
  "use workflow";

  const user = await createUser(email);
  await sendWelcomeEmail(user);

  await sleep('5s');
  await sendOnboardingEmail(user);

  console.log("Workflow is complete! Run 'npx workflow web' to inspect your run");

  return { userId: user.id, status: 'onboarded' };
}

async function createUser(email: string) {
  "use step";

  console.log('Creating user with email: ' + email);

  return { id: crypto.randomUUID(), email };
}

async function sendWelcomeEmail(user: { id: string; email: string }) {
  "use step";

  console.log('Sending welcome email to user: ' + user.id);

  if (Math.random() < 0.3) {
    throw new Error('Retryable!');
  }
}

async function sendOnboardingEmail(user: { id: string; email: string }) {
  "use step";

  if (!user.email.includes('@')) {
    throw new FatalError('Invalid Email');
  }

  console.log('Sending onboarding email to user: ' + user.id);
}
`;

const nitroConfigCodemod: CodemodDefinition = {
  globs: ['nitro.config.ts'],
  transform(source) {
    if (source.includes('workflow/nitro')) {
      return null;
    }

    const workflowModule = "  modules: ['workflow/nitro'],";

    if (source.includes('modules:')) {
      return source.replace(/modules:\s*\[([^\]]*)\]/, (_, content) => {
        const modules = content.trim()
          ? `${content}, 'workflow/nitro'`
          : "'workflow/nitro'";
        return `modules: [${modules}]`;
      });
    } else {
      return source.replace(
        /export default defineConfig\(\{([^}]*)\}\);/,
        (_, configContent) => {
          const hasExistingOptions = configContent.trim();
          const modulesSection = workflowModule;
          const newContent = hasExistingOptions
            ? `${configContent}\n${modulesSection}`
            : modulesSection;
          return `export default defineConfig({\n${newContent}\n});`;
        }
      );
    }
  },
};

const nitroRouteCodemod: CodemodDefinition = {
  globs: ['server/api/**/*.ts'],
  transform() {
    // This codemod is just to ensure the API route file exists
    // The actual content is already generated by the template
    return null;
  },
};

const nitroWorkflowCodemod: CodemodDefinition = {
  globs: ['workflows/user-signup.ts'],
  transform(source) {
    if (!source.includes('__WORKFLOW_NITRO_MINIMAL__')) {
      return null;
    }
    return nitroWorkflowContent;
  },
};

const nitroTsconfigCodemod: CodemodDefinition = {
  globs: ['tsconfig.json'],
  transform(source) {
    const parsed = parseJsonWithComments(source);
    if (!parsed) {
      return null;
    }
    parsed.compilerOptions ??= {};
    const compilerOptions = parsed.compilerOptions as Record<string, unknown>;
    const plugins = Array.isArray(compilerOptions.plugins)
      ? (compilerOptions.plugins as Record<string, unknown>[])
      : [];

    if (
      plugins.some(
        (plugin) =>
          plugin && typeof plugin === 'object' && plugin.name === 'workflow'
      )
    ) {
      return null;
    }

    const normalized = plugins.filter(
      (plugin): plugin is Record<string, unknown> =>
        Boolean(plugin && typeof plugin === 'object')
    );
    normalized.push({ name: 'workflow' });
    compilerOptions.plugins = normalized;

    return `${JSON.stringify(parsed, null, 2)}\n`;
  },
};

const nitroPackageScriptsCodemod: CodemodDefinition = {
  globs: ['package.json'],
  transform(source) {
    let parsed: any;
    try {
      parsed = JSON.parse(source);
    } catch {
      return null;
    }

    parsed.scripts ??= {};
    const scripts = parsed.scripts as Record<string, string>;
    let mutated = false;

    if (scripts.dev !== 'nitro dev') {
      scripts.dev = 'nitro dev';
      mutated = true;
    }

    if (scripts.build !== 'nitro build') {
      scripts.build = 'nitro build';
      mutated = true;
    }

    if (scripts.preview !== 'nitro preview') {
      scripts.preview = 'nitro preview';
      mutated = true;
    }

    return mutated ? `${JSON.stringify(parsed, null, 2)}\n` : null;
  },
};

function parseJsonWithComments(source: string): any | null {
  try {
    const withoutBlockComments = source.replace(/\/\*[\s\S]*?\*\//g, '');
    const withoutLineComments = withoutBlockComments.replace(/\/\/.*$/gm, '');
    return JSON.parse(withoutLineComments);
  } catch {
    return null;
  }
}

export const nitroCodemods = {
  'nitro/config/with-workflow': nitroConfigCodemod,
  'nitro/api/route': nitroRouteCodemod,
  'nitro/workflow': nitroWorkflowCodemod,
  'nitro/tsconfig/plugin': nitroTsconfigCodemod,
  'nitro/package/scripts': nitroPackageScriptsCodemod,
} as const satisfies Record<string, CodemodDefinition>;
