name = "workflow-svelte-cf-app"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./.svelte-kit/cloudflare/index.js"

[build]
command = "pnpm build"

[assets]
directory = "./dist"
binding = "ASSETS"

[[services]]
binding = "WORKFLOW_RUNTIME"
service = "my-cloudflare-world"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
WORKFLOW_TARGET_WORLD = "workflow-cloudflare-world"